{% set name = "websocket" %}
{% set version = "0.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/websocket-{{ version }}.tar.gz
  sha256: 42b506fae914ac5ed654e23ba9742e6a342b1a1c3eb92632b6166c65256469a4

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - gevent
    - greenlet

test:
  imports:
    - websocket
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://pypi.python.org/pypi/websocket
  summary: Websocket implementation for gevent
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
